### PR TITLE
291 static edit

### PR DESCRIPTION
**Pull request by dethe**
This adds static text for the edit view, including case and method id/titles, user id/titles (err, names), and other fields organized by name.

There are some more static fields I need to add, and some updating of the database table for the edit fields to match changes to the view fields, but I wanted to find out if this organizational structure works for the frontend templates OK.

Requires a database migration. After pulling this update run `npm run migratelocal 24`

Test by viewing `http://localhost:3001/case/100/edit?returns=json`

### CODE REVIEW

**Comment by ascott** [comment]
hey @dethe, thanks for this!

i ran the migration and got some errors: 
```
$ npm run migratelocal 24

> participedia@4.0.0 migratelocal /Users/alannascott/code/participedia/api
> f(){ printf -v item "%03d" $1 && echo ${item} && psql -d "${DATABASE_URL}" -f "migrations/migration_${item}.sql"; };f "24"

024
psql:migrations/migration_024.sql:2: NOTICE:  type "cases" does not exist, skipping
DROP FUNCTION
psql:migrations/migration_024.sql:3: NOTICE:  type "cases" does not exist, skipping
DROP FUNCTION
psql:migrations/migration_024.sql:9: NOTICE:  function get_case_by_id(pg_catalog.int4,text,pg_catalog.int4) does not exist, skipping
DROP FUNCTION
psql:migrations/migration_024.sql:91: ERROR:  type "full_case" does not exist
psql:migrations/migration_024.sql:102: ERROR:  type "full_case" does not exist
psql:migrations/migration_024.sql:112: ERROR:  type "full_case" does not exist
```

and then went to test the view/json response at `http://localhost:3001/case/100/edit?returns=json` and got these errors:
```
[apicache] bypass detected, skipping cache.
Executing query SELECT row_to_json(get_case_edit_by_id('100', 'en', null)) AS results ;
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { error: function get_case_edit_by_id(unknown, unknown, unknown) does not exist
    at Connection.parseE (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:114:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'error',
  length: 239,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '20',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '528',
  routine: 'ParseFuncOrColumn' } }  reason:  { error: function get_case_edit_by_id(unknown, unknown, unknown) does not exist
    at Connection.parseE (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/alannascott/code/participedia/api/node_modules/pg/lib/connection.js:114:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
  name: 'error',
  length: 239,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '20',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '528',
  routine: 'ParseFuncOrColumn' }
```

**Comment by dethe** [comment]
OK, that's weird. If cases didn't exist then nothing should have worked. You were able to get JSON results before, right?

Did you get any errors in the initial JSON import and migrations?

**Comment by dethe** [comment]
I can put together a data dump that you can import at one go instead of running migrations, the migrations are mainly needed for the live site, but they should work for both of us on our locals if all the migrations before them have run.

**Comment by dethe** [comment]
@ascott Can you run `npm run resetlocaldb` and let me know if there are any errors?  If all goes well, then running `npm run migratelocal 24` should work after that. If there are errors in resetlocaldb then we'll need to fix that first.

**Comment by ascott** [comment]
@dethe i ran `npm run resetlocaldb` successfully and then ran the migration again, and still getting the same errors.

**Comment by dethe** [comment]
OK, I knew I was tired last night, but this is ridiculous. I somehow managed to delete a critical function after I finished testing it last night, but before I committed it. Can you pull again and try `npm run migratelocal 24`. It should skip some of the steps that it has already run, but then the API URL should work. If not, I will have to debug it tomorrow.

**Pull request merged**
