### PR TITLE
Update research page with real-time data downloads section

### PR DESCRIPTION
**Pull request by ascott**
## Description
- update research page with real-time data downloads section
- add a Graph Commons network map of data structure to new section
https://graphcommons.com/graphs/d743b2ae-3da8-43a3-821a-6bc05f6d103c?auto=true
- on large screens, open all accordions on page load

## Context/Issue Link
https://github.com/participedia/api/issues/896

## Screenshots (if it's a frontend change)
Screen Shot 2020-06-10 at 5 03 01 PM

### CODE REVIEW

**Comment by jesicarson** [comment]
@ascott I assume the graph image redirects people to the graphcommons site? or does the graph load in the research page?

**Comment by ascott** [comment]
@jesicarson the graph will load in page, and also you can click the graph commons text in the bottom left once you are viewing the graph in the page.

**Comment by jesicarson** [comment]
very cool. i don't suppose the graph could be pre-loaded so we don't have to click it to load?

**Comment by ascott** [comment]
@jesicarson looked at the options, and it is possible to have it load straight away 👍 

Screen Shot 2020-06-11 at 11 10 54 AM

**Comment by jesicarson** [comment]
love it

**Comment by jesicarson** [comment]
we may want to add a very short description about what the graph is showing. Something like...

The graph below is a visual representation of all the data fields for cases, methods and organizations entries, and how they are linked. For example, all three entry types share the "scope of influence" field, while only cases have a field for "legality."

**Pull request merged**
