### PR TITLE
script to fix lat/lng for cases and organizations

### PR DESCRIPTION
**Pull request by ascott**
@dethe here is my first run at fixing  lat/lng for cases and organizations. 

https://github.com/participedia/usersnaps/issues/351
https://github.com/participedia/api/issues/478

for all cases and organizations
- compose an address string from the following article
  location keys: address1, city, province, postal_code, country.
- if no address string exists (meaning location keys are all falsey),
   save lat/lng as null
- if address string exists, pass that address string to geocode
  service to get lat/lng and save new lat/lng.

running this script will fix the articles in the local db, but we will still need to fix the migration fixtures (ie: https://github.com/participedia/api/blob/master/migrations/cases.json) so when the db is reset we have the correct lat/lng data. any suggestions on best way to do this? i took a stab at generating the new fixtures by pulling the data from the db once this migration was run, and then writing a new fixture json file. but then when i run the migrations, i get errors and the case table doesn't get populated. how did you generate the existing json fixtures?

### CODE REVIEW

**Comment by dethe** [comment]
The JSON fixtures come from the old dataset, so we can't just fix it there or when we run migrations on .xyz it will go kablooey (that's the technical term). I'll need to write a migration that creates a new column for lat/long, converts the existing value into the new column, [optionally] deletes the old columns, and serves the new column as part of the JSON result.

**Comment by dethe** [comment]
We are only converting existing lat/long format, not craziness like changing projections so I think we can just parse the fields and do the math, no geocode service needed, unless I'm missing something. Basically, what is done here: https://adamprescott.net/2013/07/17/convert-latitudelongitude-between-decimal-and-degreesminutesseconds-in-c/ but in SQL or one of the supported languages inside Postgres. I'll take a stab at that migration.

**Comment by ascott** [comment]
@dethe since your other PR takes care of the migration, i updated this PR to only include the one-off script to geocode an address and save the lat/lng.

**Comment by dethe** [comment]
@ascott OK, is this PR safe to merge then?

**Comment by ascott** [comment]
@dethe :shipit:

**Pull request merged**
