### PR TITLE
edit forms: improve request timeout/server unavailable error handling for users

### PR DESCRIPTION
**Pull request by ascott**
creates a better user experience in cases where the server takes a long time to respond. currently if the server responds with a 503 error, the client doesn't handle it gracefully which results in the page just hanging on the publishing modal. 

related issues: 
https://github.com/participedia/usersnaps/issues/826
https://github.com/participedia/usersnaps/issues/805

this change adds a max request timeout of 10 seconds when adding or editing an article. if the response takes longer than 10s we send a 408 error back to the client and show the user the "Sorry something went wrong message." This allows the user to close the error so they can try submitting the form again.  If the server had crashed, they might be logged out, and so they will get the sorry you are logged out error, which will take them through the refresh login flow, and back to their article so they can submit again (without losing their inputted data). Here is a gif of that simulated flow:

participedia-server-time-out

we also want to solve the server issue of the server time-ing out, but this will at least improve the user experience when it does happen.

### CODE REVIEW

**Comment by jesicarson** [comment]
@ascott  I cant read the popups in the gif, what do they say? Thanks!

**Comment by ascott** [comment]
@jesicarson  here are user feedback modals. let me know if you have any ideas of how to improve this. ideally the user won't see this flow very often once we get the underlying server issues resolved.

- user starts publishing entry
image

- request/server timeout happens on server
image

- user is logged out because server has restarted
image

**Comment by jesicarson** [comment]
I think this is fine as is, but you can take or leave this feedback:
 
Only improvement I could see might be eliminating the "Sorry, something went wrong. Please try again" modal - what happens when they click ok? does it go directly to the next modal, or do they return to the form and have to click publish again? 

Why not just show the "refresh session" modal straight from the timeout error? (and also, you could change the wording from "save your changes" to "publish your changes" but that's nit picky)

**Comment by ascott** [comment]
> Only improvement I could see might be eliminating the "Sorry, something went wrong. Please try again" modal - what happens when they click ok? does it go directly to the next modal, or do they return to the form and have to click publish again?

when they click ok they have to press publish again before going to the next modal, but i might be able to change that so it automatically tries to publish again. i'll try that.

**Comment by ascott** [comment]
i updated the wording in the modal and changed things so if there is a timeout error, we automatically re-try 10 times while showing the publishing modal, rather than showing the "sorry, something went wrong modal". if after 10 attempts it doesn't work, we show the "sorry something went wrong" modal.

**Pull request merged**
