### PR TITLE
map overlay and legend

### PR DESCRIPTION
**Pull request by ascott**
desktop:
Screenshot 2019-05-27 20 34 54
Screenshot 2019-05-27 20 34 45

mobile:
Screenshot 2019-05-27 20 14 54
Screenshot 2019-05-27 20 37 02

@jesicarson

### CODE REVIEW

**Comment by jesicarson** [comment]
@ascott this is looking good!
Couple things:
1. Centre the tagline text vertically between the bottom of the top nav bar and the top of the join now button (move it down on desktop)
2. I'm leaning towards removing the legend on mobile - far right option below. Reason being that the more I look at it, the more the legend looks "clickable" on the small mobile screen (which is bad, as it isn't). But the other two layouts are up for consideration. Thoughts?
Screen Shot 2019-05-28 at 12 18 26 PM

**Comment by jesicarson** [comment]
Also, @ascott - I think we need to decrease the size of the map pins to match the size of the icons used in the legend. I know i had you increase them at one point, but they are making the map feel too blobby (yes, that's a technical term, lol).

**Comment by ascott** [comment]
@jesicarson thanks for the feedback! i can make these tweaks. in terms of the mobile legend, i think the middle option looks the best to me. it makes sense to keep the legend on mobile as well so it's clear what the different color pins on the map represent.

**Comment by jesicarson** [comment]
@ascott Sounds good! Please go ahead with the middle option for mobile.

**Comment by ascott** [comment]
updated screen shots for you @jesicarson. if this is looking good i can ship to staging for you to take a closer look.

desktop:
Screenshot 2019-05-28 15 57 23
Screenshot 2019-05-28 15 57 35
Screenshot 2019-05-28 15 58 21

medium screen width:
Screenshot 2019-05-28 15 58 45
Screenshot 2019-05-28 15 58 52

smallest screen width:
Screenshot 2019-05-28 15 59 40
Screenshot 2019-05-28 15 59 29

**Comment by jesicarson** [comment]
yep ready to roll to staging for testing. thanks @ascott !!

**Comment by jesicarson** [comment]
@ascott do you think the join now button should persist on the map when it's activated? until logged in that is?

**Comment by jesicarson** [comment]
@ascott also, tiny detail but the map pins should match the size of the icon pins in the legend. they look a tad too small in the last screenshots.

**Comment by ascott** [comment]
@jesicarson i think it works well in the info overlay, and since the user can always return the overlay it makes sense to me to just leave it there.

**Comment by jesicarson** [comment]
@ascott ok thats fine. which makes me think: should the join now button disappear if a **logged in** user clicks the info icon and brings the map overlay back up?

**Comment by ascott** [comment]
@jesicarson yes, currently the join now button is not shown if the user is logged in

**Pull request merged**
