### PR TITLE
updates the "Do Full Version" flow

### PR DESCRIPTION
**Pull request by ascott**
Updates the "Do Full Version" flow, so we show the full version fields without saving the current changes or discarding them.

participedia-do-full-version-flow-2

fixes: https://github.com/participedia/usersnaps/issues/651

@jesicarson

### CODE REVIEW

**Comment by jesicarson** [comment]
The thing is, people might not want to publish yet, if their entry is still a draft. Can we keep it the way it was working on xyz, so that you could just load the full form by clicking do full version (without publishing first?)

**Comment by ascott** [comment]
I didn't think i could make this work without saving the form data first, but i'm now realizing that I might be able to do it another way so that it doesn't get published. I'll see if I can get that to work. It's actually simpler, so not sure why I didn't think of that earlier. ^_^

**Comment by jesicarson** [comment]
thanks!

**Comment by ascott** [comment]
@jesicarson i updated the gif in the description. this way the changes don't get saved, but they don't get discarded either.

**Comment by jesicarson** [comment]
perfect

**Pull request merged**
