### PR TITLE
Case Edit -- Edit Submission Details 

### PR DESCRIPTION
**Pull request by ascott**
- implements editing of submission details using an autocomplete drop down for author names

participedia-edit-submission-details
@jesicarson, i simplified the edit button until we implement the other admin functionality. does that work for now? 

@dethe, I need a couple things from the backend to complete this
- [x] add isAdmin flag to json blob
- [x] add author data to json blob (an array of objects with user_id and name keys)

### CODE REVIEW

**Comment by jesicarson** [comment]
@ascott works for me!

**Comment by dethe** [comment]
@ascott I have authors as a list of who made changes when, but you just want id/name pairs with no repeats, yes?

**Comment by dethe** [comment]
If you use the `?user=[id]` hack, the user object does have `isadmin` as a boolean.

**Comment by dethe** [comment]
PR #410 adds the `authors` field. It will be populated with names and ids of all the users if the current user is an admin, or an empty list otherwise.

**Pull request merged**
